# Generated by Django 4.2.1 on 2023-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('source', models.URLField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.URLField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
